version: "3"
services:
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 31000:3000
    volumes:
      - .:/app
    links:
      - "postgres-db:database"
  postgres-db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 31543:5432
    volumes:
      - /home/giova/repositories/tdd-database-2/data:/var/lib/postgresql/data